# Generated by Django 5.2.8 on 2025-12-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updated',
            new_name='update',
        ),
    ]
